#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : chrpath
Version  : 0.16
Release  : 8
URL      : https://alioth-archive.debian.org/releases/chrpath/chrpath/0.16/chrpath-0.16.tar.gz
Source0  : https://alioth-archive.debian.org/releases/chrpath/chrpath/0.16/chrpath-0.16.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: chrpath-bin = %{version}-%{release}
Requires: chrpath-license = %{version}-%{release}
Requires: chrpath-man = %{version}-%{release}

%description
chrpath
=======
chrpath allows you to modify the dynamic library load path (rpath) of
compiled programs.  Currently, only removing and modifying the rpath
is supported.  Eventually, I hope to be able to add an rpath if it is
missing.

%package bin
Summary: bin components for the chrpath package.
Group: Binaries
Requires: chrpath-license = %{version}-%{release}
Requires: chrpath-man = %{version}-%{release}

%description bin
bin components for the chrpath package.


%package license
Summary: license components for the chrpath package.
Group: Default

%description license
license components for the chrpath package.


%package man
Summary: man components for the chrpath package.
Group: Default

%description man
man components for the chrpath package.


%prep
%setup -q -n chrpath-0.16

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1540234348
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1540234348
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/chrpath
cp COPYING %{buildroot}/usr/share/package-licenses/chrpath/COPYING
cp deb/copyright %{buildroot}/usr/share/package-licenses/chrpath/deb_copyright
%make_install

%files
%defattr(-,root,root,-)
/usr/doc/chrpath-0.16/AUTHORS
/usr/doc/chrpath-0.16/COPYING
/usr/doc/chrpath-0.16/ChangeLog
/usr/doc/chrpath-0.16/INSTALL
/usr/doc/chrpath-0.16/NEWS
/usr/doc/chrpath-0.16/README

%files bin
%defattr(-,root,root,-)
/usr/bin/chrpath

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/chrpath/COPYING
/usr/share/package-licenses/chrpath/deb_copyright

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/chrpath.1
